### ISSUE TITLE
today,it doesn't work ,but it did work yestoday

### ISSUE THREAD

**Issue by ghn9264** [wechaty/getting-started#241]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
![image](https://user-images.githubusercontent.com/32256957/147775015-e7200346-a683-4445-b95a-a0fc3ad494b5.png)

**Comment by huan** [comment]
Merge to

- https://github.com/wechaty/puppet-wechat/issues/192
