### ISSUE TITLE
https://wechaty.js.org/qrcode 二維碼打不開了

### ISSUE THREAD

**Issue by kongdekede** [wechaty/getting-started#251]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by huan** [comment]
The dev.chatie.io server has been down.

We are trying to bring it back online now.

**Comment by huan** [comment]
Update: wechaty.js.org service restored.
