### ISSUE TITLE
Wechaty unhandledRejection: TypeError: qrTerm.generate is not a function

### ISSUE THREAD

**Issue by FatLi1989** [wechaty/getting-started#253]
window 系统启动wechaty时
Wechaty unhandledRejection: TypeError: qrTerm.generate is not a function

**Comment by huan** [comment]
The official getting started ding-dong-bot.ts should work. 

See:

https://github.com/wechaty/getting-started/blob/6d36dd93f80f5cf31054aab00e99121c77e31a8b/examples/ding-dong-bot.ts#L18-L28
