### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by sennpang** [wechaty/getting-started#261]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: "wechaty": "^1.18.1",

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: wechaty-puppet-padlocal

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: wechaty-puppet-padlocal

- What is your node version? (run `node --version`)
Answer: v17.9.0

- What os are you using
Answer: MacOS

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. git clone https://github.com/wechaty/getting-started.git
2. cd getting-started
3. npm i
4. npm i wechaty-puppet-padlocal
5. npm start

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
> wechaty-getting-started@1.18.7 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

09:40:05 INFO Config registering process.on("unhandledRejection") for development/debug
09:40:05 VERB Config constructor()
09:40:05 VERB PoolifyMixin poolifyMixin(EventEmitter)
09:40:05 VERB WechatifyMixin wechatifyMixin(AbstractPoolifyMixin)
09:40:05 VERB ValidationMixin validationMixin(ContactMixin)
09:40:05 VERB ValidationMixin validationMixin(ContactImplBase)
09:40:05 VERB PoolifyMixin poolifyMixin(ContactImpl)
09:40:05 VERB ValidationMixin validationMixin(ContactSelfMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(FavoriteMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EventEmitter)
09:40:05 VERB ValidationMixin validationMixin(FriendshipMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(ImageMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(LocationMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(PostMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EventEmitter)
09:40:05 VERB ValidationMixin validationMixin(MessageMixin)
09:40:05 VERB ValidationMixin validationMixin(MessageImplBase)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(MiniProgramMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(MomentMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(MoneyMixin)
09:40:05 VERB PoolifyMixin poolifyMixin(EventEmitter)
09:40:05 VERB WechatifyMixin wechatifyMixin(AbstractPoolifyMixin)
09:40:05 VERB ValidationMixin validationMixin(RoomMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(RoomInvitationMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB PoolifyMixin poolifyMixin(AbstractWechatifyMixin)
09:40:05 VERB ValidationMixin validationMixin(TagMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(UrlLinkMixin)
09:40:05 VERB WechatifyMixin wechatifyMixin(EmptyBase)
09:40:05 VERB ValidationMixin validationMixin(DelayMixin)
09:40:05 VERB WechatyGErrorMixin gErrorMixin(WechatySkeleton)
09:40:05 VERB WechatifyUserModuleMixin wechatifyUserModuleMixin(GErrorMixin)
09:40:05 VERB WechatyIoMixin ioMixin(WechatifyUserModuleMixin)
09:40:05 VERB WechatyPuppetMixin puppetMixin(IoMixin)
09:40:05 VERB WechatyLoginMixin loginMixin(PuppetMixin)
09:40:05 VERB WechatyMiscMixin miscMixin(LoginMixin)
09:40:05 VERB WechatyPluginMixin pluginMixin(MiscMixin)
09:40:05 VERB ValidationMixin validationMixin(WechatyBase)
09:40:05 VERB ValidationMixin validationMixin(WechatyImplBase)
09:40:05 VERB wechaty-puppet-service monkeyPatchMetadataFromHttp2Headers()
09:40:05 VERB WechatyBuilder singleton()
09:40:05 VERB WechatyBuilder newInstance()
09:40:05 VERB WechatyLoginMixin constructor()
09:40:05 VERB WechatyPuppetMixin construct()
09:40:05 VERB WechatyIoMixin constructor()
09:40:05 VERB WechatifyUserModuleMixin constructor()
09:40:05 VERB WechatySkeleton constructor()
09:40:05 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
09:40:05 VERB ServiceCtl<Wechaty> constructor()
09:40:05 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
09:40:05 VERB StateSwitch constructor(WechatyReset, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
09:40:05 VERB Wechaty constructor()
09:40:05 VERB WechatySkeleton on(scan, listener) registering... listenerCount: 0
09:40:05 VERB WechatySkeleton on(login, listener) registering... listenerCount: 0
09:40:05 VERB WechatySkeleton on(logout, listener) registering... listenerCount: 0
09:40:05 VERB WechatySkeleton on(message, listener) registering... listenerCount: 0
09:40:05 VERB Wechaty start()
09:40:05 VERB WechatyLoginMixin init()
09:40:05 VERB WechatyPuppetMixin init()
09:40:05 VERB WechatifyUserModuleMixin init()
09:40:05 VERB WechatySkeleton init()
09:40:05 VERB WechatifyUserModuleMixin init() initializing Wechaty User Module (WUM) ...
09:40:05 VERB WechatifyMixin wechatifyUserModule(ContactImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(ContactImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(ContactSelfImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(ContactSelfImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(DelayImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(DelayImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(FriendshipImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(FriendshipImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(ImageImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(ImageImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(LocationImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(LocationImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(MessageImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(MessageImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(MiniProgramImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(MiniProgramImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(PostImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(PostImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(RoomImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(RoomImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(RoomInvitationImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(RoomInvitationImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(TagImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(TagImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyMixin wechatifyUserModule(UrlLinkImpl)
09:40:05 VERB WechatifyMixin wechatifyUserModule(UrlLinkImpl)(Wechaty#4595ca47-8290-43f9-98dd-9e4ac81a14a6<>(ding-dong-bot))
09:40:05 VERB WechatifyUserModuleMixin init() initializing Wechaty User Module (WUM) ... done
09:40:05 VERB WechatyPuppetMixin init() instanciating puppet instance ...
09:40:05 VERB Puppet resolvePuppet({puppet: wechaty-puppet-padlocal, puppetOptions: {}})
09:40:05 VERB Puppet resolvePuppet() resolving name "wechaty-puppet-padlocal" ...
09:40:05 VERB Puppet resolvePuppetName(wechaty-puppet-padlocal)
09:40:05 VERB Wechaty init() Raven disabled (import("raven") failed)
09:40:05 VERB Puppet resolvePuppetName(wechaty-puppet-padlocal): CJS resolved, retry times: 1
09:40:05 VERB Puppet resolvePuppet() resolving name "wechaty-puppet-padlocal" ... done
09:40:05 VERB Puppet resolvePuppet() instanciating puppet ...
09:40:05 VERB PuppetSkeleton constructor({})
09:40:05 VERB PuppetMemoryMixin constructor()
09:40:05 VERB PuppetLoginMixin constructor()
09:40:05 VERB PuppetCacheMixin constructor()
09:40:05 VERB PuppetCacheAgent constructor()
09:40:05 VERB PuppetContactMixin constructor()
09:40:05 VERB PuppetRoomMemberMixin constructor()
09:40:05 VERB PuppetRoomMixin constructor()
09:40:05 VERB PuppetFriendshipMixin constructor()
09:40:05 VERB PuppetTagMixin constructor()
09:40:05 VERB PuppetRoomInvitationMixin constructor()
09:40:05 VERB PuppetMessageMixin constructor()
09:40:05 VERB PuppetMiscMixin constructor()
09:40:05 VERB ServiceCtl<PuppetServiceMixin> constructor()
09:40:05 VERB StateSwitch constructor(PuppetServiceMixin, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
09:40:05 VERB StateSwitch constructor(PuppetServiceMixinReset, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
09:40:05 VERB PuppetServiceMixin constructor() #0
09:40:05 VERB PuppetWatchdogAgent constructor(e2c61b89-414c-4f45-8e42-ed403b886ada)
09:40:05 VERB PuppetWatchdogAgent constructor() timeout 60 seconds
09:40:05 VERB ReadyMixin constructor()
09:40:05 VERB PuppetPostMixin constructor()
09:40:05 VERB PuppetSayableMixin constructor()
09:40:05 VERB TapMixin constructor()
09:40:05 VERB Puppet constructor({})
09:40:05 VERB Puppet resolvePuppet() instanciating puppet ... done
09:40:05 VERB WechatyPuppetMixin init() instanciating puppet instance ... done
09:40:05 VERB WechatyPuppetMixin init() setting memory ...
09:40:05 VERB PuppetMemoryMixin setMemory(ding-dong-bot)
09:40:05 VERB WechatyPuppetMixin init() setting memory ... done
09:40:05 VERB WechatyPuppetMixin init() setting up events ...
09:40:05 VERB WechatyPuppetMixin __setupPuppetEvents(Puppet<PuppetPadlocal>(ding-dong-bot))
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(friendship) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(login) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(logout) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(message) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(post) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-invite) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-join) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-leave) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-topic) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(scan) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(dirty) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(dong) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(error) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(heartbeat) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(ready) (listenerCount:0) registering...
09:40:05 VERB PuppetMixin __setupPuppetEvents() puppet.on(reset) (listenerCount:0) registering...
09:40:05 VERB WechatyPuppetMixin __setupPuppetEvents() ... done
09:40:05 VERB WechatyPuppetMixin init() setting up events ... done
09:40:05 VERB WechatyPuppetMixin init() emitting "puppet" event ...
09:40:05 VERB WechatyPuppetMixin init() emitting "puppet" event ... done
09:40:05 VERB ServiceCtl<Wechaty> start()
09:40:05 VERB StateSwitch <Wechaty> active(pending) <- (false)
09:40:05 VERB ServiceCtl<Wechaty> start() super.start() ...
09:40:05 VERB WechatyPuppetMixin start()
09:40:05 VERB WechatyPuppetMixin start() super.start() ...
09:40:05 VERB WechatyIoMixin start()
09:40:05 VERB WechatySkeleton start()
09:40:05 VERB WechatyLoginMixin init()
09:40:05 VERB WechatyPuppetMixin init()
09:40:05 VERB WechatifyUserModuleMixin init()
09:40:05 VERB WechatySkeleton init()
09:40:05 VERB WechatifyUserModuleMixin init() Wechaty User Module (WUM)s have already wechatified: skip
09:40:05 VERB WechatyPuppetMixin init() skipped because this puppet has already been inited before.
09:40:05 VERB WechatyPuppetMixin start() super.start() ... done
09:40:05 VERB WechatyPuppetMixin start() starting puppet ...
09:40:05 ERR StarterBot TypeError: The "listener" argument must be of type function. Received undefined
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by acheong08** [comment]
Why was this closed? How was it solved?

**Comment by sennpang** [comment]
> Why was this closed? How was it solved?

cd getting-started
git checkout v0.x
npm install
npm start
